import React, { useMemo, useState } from 'react';
import { View, Text, StyleSheet, Pressable, ScrollView, Alert } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation, useRoute } from '@react-navigation/native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { useAuth } from '../auth/AuthContext';
import { formatNaira } from '../lib/money';
import { Txn } from '../components/TransactionRow';
import { font, radius, spacing } from '../theme';
import { useTheme, Palette } from '../theme/ThemeContext';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function formatDateTime(iso: string): string {
  const d = new Date(iso);
  const hh = d.getHours() % 12 || 12;
  const mm = String(d.getMinutes()).padStart(2, '0');
  const ap = d.getHours() < 12 ? 'AM' : 'PM';
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()}, ${hh}:${mm} ${ap}`;
}

function statusMeta(state: string, colors: Palette): { label: string; color: string } {
  if (['completed', 'payout_sent'].includes(state)) return { label: 'Completed', color: colors.success };
  if (state === 'reversed') return { label: 'Refunded', color: colors.inkSoft };
  if (['payout_failed', 'reversing'].includes(state)) return { label: 'Refunding', color: colors.warning };
  if (state === 'failed') return { label: 'Failed', color: colors.danger };
  if (['payer_charged', 'payout_pending', 'authorized', 'pending'].includes(state)) return { label: 'Processing', color: colors.warning };
  return { label: 'Pending', color: colors.muted };
}

type Step = { label: string; done: boolean; tone?: 'warn' | 'danger' };

function buildTimeline(state: string): Step[] {
  if (['payout_failed', 'reversing', 'reversed'].includes(state)) {
    return [
      { label: 'Payment initiated', done: true },
      { label: 'Card charged', done: true },
      { label: 'Payout failed', done: true, tone: 'warn' },
      { label: 'Refunded to payer', done: state === 'reversed', tone: 'warn' },
    ];
  }
  if (state === 'failed') {
    return [
      { label: 'Payment initiated', done: true },
      { label: 'Failed', done: true, tone: 'danger' },
    ];
  }
  const order = ['pending', 'authorized', 'payer_charged', 'payout_pending', 'payout_sent', 'completed'];
  const idx = order.indexOf(state);
  const reached = (i: number) => idx >= i;
  return [
    { label: 'Payment initiated', done: reached(0) },
    { label: 'Card charged', done: reached(2) },
    { label: 'Paid out', done: reached(4) },
    { label: 'Completed', done: reached(5) },
  ];
}

function receiptHtml(txn: Txn, statusLabel: string): string {
  const received = txn.direction === 'received';
  const sign = received ? '+' : '-';
  const amount = `${sign}${formatNaira(txn.amountKobo)}`;
  const partyLabel = received ? 'From' : 'To';
  return `
  <html><head><meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { font-family: -apple-system, Helvetica, Arial, sans-serif; box-sizing: border-box; }
    body { margin: 0; padding: 32px; color: #0B1020; }
    .card { max-width: 520px; margin: 0 auto; border: 1px solid #ECEEF4; border-radius: 18px; overflow: hidden; }
    .head { background: #4F46E5; color: #fff; padding: 28px 28px 24px; }
    .brand { font-weight: 800; font-size: 20px; letter-spacing: .3px; }
    .tag { opacity: .85; font-size: 13px; margin-top: 4px; }
    .amount { font-size: 38px; font-weight: 800; margin: 22px 28px 6px; color: ${received ? '#12B76A' : '#0B1020'}; }
    .status { display:inline-block; margin: 0 28px 20px; font-size: 13px; font-weight: 600; color:#434A63; }
    table { width: calc(100% - 56px); margin: 0 28px 24px; border-collapse: collapse; }
    td { padding: 12px 0; font-size: 14px; border-bottom: 1px solid #F2F3F8; }
    td.k { color: #8E93A6; } td.v { text-align: right; font-weight: 600; }
    .foot { text-align:center; color:#8E93A6; font-size:12px; padding: 4px 28px 28px; }
  </style></head>
  <body><div class="card">
    <div class="head"><div class="brand">PayXchange</div><div class="tag">Payment receipt</div></div>
    <div class="amount">${amount}</div>
    <div class="status">${statusLabel}</div>
    <table>
      <tr><td class="k">${partyLabel}</td><td class="v">${txn.counterparty}</td></tr>
      ${txn.description ? `<tr><td class="k">Description</td><td class="v">${txn.description}</td></tr>` : ''}
      <tr><td class="k">Type</td><td class="v">${received ? 'Received' : 'Sent'}</td></tr>
      <tr><td class="k">Date</td><td class="v">${formatDateTime(txn.createdAt)}</td></tr>
      <tr><td class="k">Reference</td><td class="v">${txn.id}</td></tr>
    </table>
    <div class="foot">Generated by PayXchange • Keep this as proof of payment</div>
  </div></body></html>`;
}

export default function TransactionDetailScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<any>();
  const route = useRoute<any>();
  const { colors } = useTheme();
  const styles = useMemo(() => makeStyles(colors), [colors]);
  const { setLockSuspended } = useAuth();
  const [sharing, setSharing] = useState(false);

  const txn: Txn = route.params?.txn;
  if (!txn) {
    return (
      <View style={[styles.fill, { paddingTop: insets.top + spacing.xl, alignItems: 'center' }]}>
        <Text style={styles.muted}>Transaction not found.</Text>
      </View>
    );
  }

  const received = txn.direction === 'received';
  const status = statusMeta(txn.state, colors);
  const timeline = buildTimeline(txn.state);

  const shareReceipt = async () => {
    setSharing(true);
    setLockSuspended(true); // the share sheet backgrounds the app — don't lock
    try {
      // In Expo Go the Print cache file is sandboxed and unreadable by other
      // modules — so get the PDF as base64 in memory and write our own copy
      // into the document dir, which is shareable.
      const { base64 } = await Print.printToFileAsync({ html: receiptHtml(txn, status.label), base64: true });
      if (!base64) throw new Error('Could not render the receipt.');
      const dest = `${FileSystem.documentDirectory}PayXchange-receipt-${Date.now()}.pdf`;
      await FileSystem.writeAsStringAsync(dest, base64, { encoding: FileSystem.EncodingType.Base64 });

      const available = await Sharing.isAvailableAsync();
      if (!available) {
        Alert.alert('Sharing unavailable', 'This device cannot share files.');
        return;
      }
      await Sharing.shareAsync(dest, { mimeType: 'application/pdf', dialogTitle: 'Share receipt' });
    } catch (e: any) {
      // Surface the real reason so it's not a dead end.
      Alert.alert('Could not share', String(e?.message ?? e ?? 'Unknown error'));
    } finally {
      setSharing(false);
      setTimeout(() => setLockSuspended(false), 500);
    }
  };

  return (
    <View style={styles.fill}>
      <View style={[styles.header, { paddingTop: insets.top + spacing.sm }]}>
        <Pressable onPress={() => navigation.goBack()} hitSlop={12} style={styles.back}>
          <Ionicons name="chevron-back" size={26} color={colors.ink} />
        </Pressable>
        <Text style={styles.headerTitle}>Transaction</Text>
        <View style={{ width: 26 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: spacing.xl, paddingBottom: insets.bottom + spacing.xxl }}>
        {/* Amount + status */}
        <View style={styles.hero}>
          <View style={[styles.heroIcon, { backgroundColor: received ? colors.successSoft : colors.primarySoft }]}>
            <Ionicons name={received ? 'arrow-down' : 'arrow-up'} size={26} color={received ? colors.success : colors.primary} />
          </View>
          <Text style={[styles.amount, { color: received ? colors.success : colors.ink }]}>
            {received ? '+' : '-'}
            {formatNaira(txn.amountKobo)}
          </Text>
          <View style={[styles.statusPill, { backgroundColor: status.color + '22' }]}>
            <Text style={[styles.statusText, { color: status.color }]}>{status.label}</Text>
          </View>
        </View>

        {/* Details */}
        <View style={styles.card}>
          <Detail styles={styles} k={received ? 'From' : 'To'} v={txn.counterparty} />
          {txn.description ? <Detail styles={styles} k="Description" v={txn.description} /> : null}
          <Detail styles={styles} k="Type" v={received ? 'Received' : 'Sent'} />
          <Detail styles={styles} k="Date" v={formatDateTime(txn.createdAt)} />
          <Detail styles={styles} k="Reference" v={txn.id} mono last />
        </View>

        {/* Timeline */}
        <Text style={styles.sectionTitle}>Status</Text>
        <View style={styles.card}>
          {timeline.map((s, i) => {
            const dotColor = !s.done ? colors.line : s.tone === 'danger' ? colors.danger : s.tone === 'warn' ? colors.warning : colors.success;
            return (
              <View key={i} style={styles.stepRow}>
                <View style={styles.stepRail}>
                  <View style={[styles.stepDot, { backgroundColor: dotColor }]} />
                  {i < timeline.length - 1 && <View style={[styles.stepLine, { backgroundColor: colors.line }]} />}
                </View>
                <Text style={[styles.stepLabel, { color: s.done ? colors.ink : colors.muted }]}>{s.label}</Text>
              </View>
            );
          })}
        </View>

        <Pressable
          style={({ pressed }) => [styles.shareBtn, pressed && { opacity: 0.9 }]}
          onPress={shareReceipt}
          disabled={sharing}
        >
          <Ionicons name="share-outline" size={18} color={colors.white} />
          <Text style={styles.shareText}>{sharing ? 'Preparing…' : 'Share receipt'}</Text>
        </Pressable>
      </ScrollView>
    </View>
  );
}

function Detail({ styles, k, v, mono, last }: { styles: any; k: string; v: string; mono?: boolean; last?: boolean }) {
  return (
    <View style={[styles.detailRow, last && { borderBottomWidth: 0 }]}>
      <Text style={styles.detailK}>{k}</Text>
      <Text style={[styles.detailV, mono && { fontSize: 12 }]} numberOfLines={1} ellipsizeMode="middle">
        {v}
      </Text>
    </View>
  );
}

const makeStyles = (colors: Palette) =>
  StyleSheet.create({
    fill: { flex: 1, backgroundColor: colors.bgSoft },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, paddingBottom: spacing.sm },
    back: { width: 26 },
    headerTitle: { fontFamily: font.bold, fontSize: 17, color: colors.ink },
    muted: { fontFamily: font.regular, color: colors.muted, fontSize: 15 },

    hero: { alignItems: 'center', marginBottom: spacing.xl },
    heroIcon: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md },
    amount: { fontFamily: font.extrabold, fontSize: 38, letterSpacing: -1 },
    statusPill: { paddingHorizontal: spacing.md, paddingVertical: 5, borderRadius: radius.pill, marginTop: spacing.sm },
    statusText: { fontFamily: font.semibold, fontSize: 13 },

    card: { backgroundColor: colors.card, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, paddingHorizontal: spacing.lg, marginBottom: spacing.lg },
    detailRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.line, gap: spacing.lg },
    detailK: { fontFamily: font.medium, fontSize: 14, color: colors.muted },
    detailV: { fontFamily: font.semibold, fontSize: 14, color: colors.ink, flexShrink: 1, textAlign: 'right' },

    sectionTitle: { fontFamily: font.semibold, fontSize: 13, color: colors.muted, marginBottom: spacing.sm, marginLeft: spacing.xs },
    stepRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: spacing.xs, minHeight: 40 },
    stepRail: { alignItems: 'center', width: 24 },
    stepDot: { width: 12, height: 12, borderRadius: 6, marginTop: 4 },
    stepLine: { width: 2, flex: 1, marginTop: 2, minHeight: 22 },
    stepLabel: { fontFamily: font.medium, fontSize: 15, paddingTop: 2 },

    shareBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, height: 56, borderRadius: radius.lg, backgroundColor: colors.primary, marginTop: spacing.sm },
    shareText: { fontFamily: font.bold, fontSize: 16, color: colors.white },
  });